version: '3'
services:
  database:
    build: ./db
    container_name: rest-pg-db
    #restart: always
    volumes:
      - ./db/pgdata:/pgdata
    #- ./db/postgresql.conf:$CUSTOM_CONFIG/postgresql.conf
    #command: 
    #  - postgres -c config_file=$CUSTOM_CONFIG/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rest-pg
      - PGDATA=$PGDATA
      #- PGAUTOCONF=$CUSTOM_CONFIG/postgresql.conf
      

